#端口号
server:
  port: 9080

#数据库配置
spring:
  datasource:
    username: root
    password: 1111
    url: jdbc:mysql:///jxc?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML

#Mybits的集成配置
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#上传、下载的路径
File:
  filePath: D:\IdeaProjects\Knowledge\src\main\resources\fileStores\
  zipPath: D:\Downloads\DownLoad.zip

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

  #分页的配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check